import {
  Controller,
  Get,
  Post,
  Delete,
  HttpCode,
  HttpStatus,
  Body,
  Param,
  ParseUUIDPipe,
  UseGuards,
} from '@nestjs/common';
import { AiChatService } from './ai-chat.service';
import { GetCurrentUserId } from '../common/decorators/get-current-user-id.decorator';
import { CreateMessageDto } from './dto/create-message.dto';
import { ThrottlerGuard, Throttle } from '@nestjs/throttler';
import {
  ApiBearerAuth,
  ApiOperation,
  ApiTags,
  ApiOkResponse,
  ApiCreatedResponse,
  ApiResponse,
  ApiParam,
} from '@nestjs/swagger';
import { AiConversationSummaryDto } from './dto/ai-conversation-summary.dto';
import { AiConversationDetailDto } from './dto/ai-conversation-detail.dto';
import { SendMessageResponseDto } from './dto/send-message-response.dto';

@ApiTags('AI Chat')
@ApiBearerAuth('JWT-auth')
@Controller('ai-chat')
export class AiChatController {
  constructor(private readonly aiChatService: AiChatService) {}

  @Get('conversations')
  @ApiOperation({ summary: 'Get all user conversations' })
  @ApiOkResponse({
    description:
      'Return list of conversations with the latest message preview. Titles are nullable.',
    type: [AiConversationSummaryDto],
  })
  getUserConversations(@GetCurrentUserId() userId: string) {
    return this.aiChatService.getUserConversations(userId);
  }

  @Post('conversations')
  @ApiOperation({ summary: 'Start a new conversation' })
  @ApiCreatedResponse({
    description:
      'Conversation created. Title is initially null and will be auto-generated on the first message.',
    type: AiConversationSummaryDto,
  })
  createConversation(@GetCurrentUserId() userId: string) {
    return this.aiChatService.createConversation(userId);
  }

  @Get('conversations/:id')
  @ApiOperation({ summary: 'Get a conversation by ID' })
  @ApiParam({ name: 'id', description: 'Conversation UUID' })
  @ApiOkResponse({
    description: 'Return conversation details with full message history.',
    type: AiConversationDetailDto,
  })
  getConversation(
    @GetCurrentUserId() userId: string,
    @Param('id', ParseUUIDPipe) conversationId: string,
  ) {
    return this.aiChatService.getConversation(userId, conversationId);
  }

  @Post('conversations/:id/message')
  @UseGuards(ThrottlerGuard)
  @Throttle({ default: { limit: 5, ttl: 60000 } }) // 5 messages per minute
  @ApiOperation({
    summary: 'Send a message to the AI',
    description:
      'Sends a user message and returns the AI response + analysis. Note: If this is the first message in the conversation, a short empathetic title (3-8 words) will be auto-generated by Gemini.',
  })
  @ApiParam({ name: 'id', description: 'Conversation UUID' })
  @ApiCreatedResponse({
    description: 'Message processed and AI replied.',
    type: SendMessageResponseDto,
  })
  sendMessage(
    @GetCurrentUserId() userId: string,
    @Param('id', ParseUUIDPipe) conversationId: string,
    @Body() createMessageDto: CreateMessageDto,
  ) {
    return this.aiChatService.processUserMessage(
      userId,
      conversationId,
      createMessageDto.content,
    );
  }

  @Delete('conversations')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: 'Delete all user conversations' })
  @ApiResponse({ status: 204, description: 'All conversations deleted.' })
  async clearConversations(@GetCurrentUserId() userId: string) {
    await this.aiChatService.clearUserConversations(userId);
  }

  @Delete('conversations/:id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: 'Delete a specific conversation' })
  @ApiParam({ name: 'id', description: 'Conversation UUID' })
  @ApiResponse({ status: 204, description: 'Conversation deleted.' })
  @ApiResponse({ status: 404, description: 'Conversation not found.' })
  async deleteConversation(
    @GetCurrentUserId() userId: string,
    @Param('id', ParseUUIDPipe) conversationId: string,
  ) {
    await this.aiChatService.deleteConversation(userId, conversationId);
  }
}
